IBP-4338-BrapiGetProgramsV2
IntegratedBreedingPlatform/BMSAPI pull request #481
Opened 2021-02-19 01:32 UTC by gelli-leafnode

New endpoint for Brapi get programs v2 
Retain current behavior programDbId = program_uuid 
Implement ProgramSearchRequest 
Created new fields under Programs pojo for brapiv2 
Create unit test and edit existing get programs v1

2021-02-19 02:32 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v1/program/Program.java
> +	private String programName;
provide a new line after each property

2021-02-19 02:33 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v1/program/ProgramMapper.java
> +	private static JacksonAnnotationIntrospector annotationIntrospector;
What is this for?

2021-02-19 03:24 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v2/program/ProgramResourceBrapi.java
> +            @PathVariable final String commonCropName,
As discussed,
1.  commonCropName is a filter not URL path variable
2. retrieve list of crops accessible to logged in user and only return programs for those crop/s. Perform validation that commonCropName paramter, if existing, is part of that list of crops

2021-02-19 03:26 UTC, darla-leafnode commented on src/main/java/org/ibp/api/java/program/ProgramService.java
> +	List<ProgramDetailsDto> getProgramsByFilter(final int pageNumber, final int pageSize, final ProgramSearchRequest programSearchRequest);
Use Pageable interface

2021-02-19 03:31 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v1/program/Program.java
> +	private ProgramAdditionalInfo additionalInfo;
I don't think you need ProgramAdditionalInfo class. can be just Map<String, String>

2021-02-24 05:01 UTC, abatac requested changes

2021-02-26 02:44 UTC, merged