IBP-4662 PUI name type
IntegratedBreedingPlatform/BMSAPI pull request #552
Opened 2021-07-19 12:10 UTC by darla-leafnode

2021-07-21 04:30 UTC, abatac requested changes

2021-07-22 04:04 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v2/germplasm/GermplasmImportRequestValidator.java
> +		final List<String> puisList = this.collectGermplasmPUIs(germplasmImportRequestDtoList);
Done

2021-07-22 04:04 UTC, darla-leafnode commented on src/main/java/org/ibp/api/java/impl/middleware/germplasm/GermplasmServiceImpl.java
>  	private void validateGermplasmUUID(final String germplasmUUID) {
Done

2021-07-22 04:04 UTC, darla-leafnode commented on src/main/java/org/ibp/api/java/impl/middleware/germplasm/brapi/GermplasmServiceBrapiImpl.java
> +			throw new ApiRuntimeException("An error has occurred when trying to count germplasm", e);
Done

2021-07-27 07:46 UTC, merged