IBP-4794 Manager Metadata (Name Types)
IntegratedBreedingPlatform/BMSAPI pull request #556
Opened 2021-07-28 11:56 UTC by cuenyad

Please Review.

Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1101
https://github.com/IntegratedBreedingPlatform/Workbench/pull/519

2021-07-29 14:12 UTC, clarysabel requested changes
Some comments left in the PR

2021-07-29 19:49 UTC, cuenyad commented on src/main/java/org/ibp/api/java/impl/middleware/name/validator/GermplasmNameTypeValidator.java
> +	public void deletable(final Integer nameTypeId) {
done.

2021-07-29 20:15 UTC, cuenyad commented on src/main/java/org/ibp/api/java/impl/middleware/name/validator/GermplasmNameTypeValidator.java
> +	public static final List<String> NAME_TYPES_USED_FOR_THE_SYSTEM = Collections.unmodifiableList(
done.

2021-07-29 20:19 UTC, cuenyad commented on src/main/java/org/ibp/api/java/impl/middleware/name/validator/GermplasmNameTypeValidator.java
> +		if (nameTypeDTOS.size() > 1 || nameTypeDTOS.size() == 1 && nameTypeId != null && !nameTypeDTOS.get(0).getId().equals(nameTypeId)) {
done.

2021-08-05 14:39 UTC, clarysabel commented on src/test/java/org/ibp/api/java/impl/middleware/name/GermplasmNameTypeValidatorTest.java
> +	public void ValidateDeletable_ThrowsException_WhenNameTypeIdIsInvalid() {
replace in all cases Validate by testValidate @cuenyad

2021-08-05 18:56 UTC, merged