IBP-5031: Implement POST/GET samples search
IntegratedBreedingPlatform/BMSAPI pull request #613
Opened 2021-11-11 00:53 UTC by cheryleigh

2021-11-11 03:02 UTC, mderamos requested changes

2021-11-11 07:50 UTC, mderamos requested changes

2021-11-11 07:50 UTC, mderamos commented on src/main/java/org/ibp/api/brapi/v2/SampleResourceBrapi.java
> +		@RequestParam(value = "observationUnitDbId", required = false) final String observationUnitDbIds,
change variable name to observationUnitDbId

2021-11-11 09:03 UTC, mderamos approved these changes

2021-11-17 02:21 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v2/SampleResourceBrapi.java
> +		final Result<SampleObservationDto> results = new Result<SampleObservationDto>().withData(resultPage.getPageResults());
Extract to common method:
`final Result<SampleObservationDto> results = new Result<SampleObservationDto>().withData(resultPage.getPageResults());
		final Pagination pagination = new Pagination().withPageNumber(resultPage.getPageNumber()).withPageSize(resultPage.getPageSize())
			.withTotalCount(resultPage.getTotalResults()).withTotalPages(resultPage.getTotalPages());

		final Metadata metadata = new Metadata().withPagination(pagination);
		return new ResponseEntity<>(new EntityListResponse<>(metadata, results), HttpStatus.OK);`

2021-11-17 02:22 UTC, darla-leafnode commented on src/main/java/org/ibp/api/java/impl/middleware/sample/SampleService.java
> -
Remove unused imports

2021-11-17 02:22 UTC, darla-leafnode commented on src/main/java/org/ibp/api/java/impl/middleware/sample/SampleServiceImpl.java
> -	public List<SampleObservationDto> getSampleObservations(final SampleSearchRequestDTO requestDTO, final Pageable pageable) {
Remove unused imports

2021-11-17 02:25 UTC, darla-leafnode commented on src/main/java/org/ibp/api/brapi/v2/SampleResourceBrapi.java
>  import io.swagger.annotations.ApiParam;
Move this under org.ibp.api.brapi.v2.sample package

2021-11-17 06:28 UTC, darla-leafnode approved these changes

2021-11-17 06:28 UTC, merged